### ISSUE TITLE
GetFriendlyUrl and page Shortcut

### ISSUE THREAD

**Issue by codeclever** [Geta/EPi.Extensions#32]
Hi I've noticed the GetFriendlyUrl extension doesn't account for the shortcut set on the content. I ended up passing around .LinkURL and subsequently using Url.ContentUrl in the view which solved my issue. Had a quick look in to the differences between the two but couldn't see anything obvious. Both appear to be using UrlResolver.

Thoughts?

Nice one,
Aaron.

**Comment by marisks** [comment]
Unfortunately, this issue happens because Episerver behaves differently when resolving URL by a string URL and when resolving URL by a content link.
When you have a content or content link available, you should use Episerver's API - UrlHelper.ContentUrl. When you have only string URL (also Url type), then use GetFriendlyUrl from this package.
